/home/alex/code/machineconfig/src/machineconfig/profile/create.py
  /home/alex/code/machineconfig/src/machineconfig/profile/create.py:156:39 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "object" of type "OperationRecord" in function "append"
    Type "Literal['already_linked', 'relinking', 'fixing_broken_link', 'identical_files', 'backupConfigDefaultPath', 'backing_up_target', 'relink2newSelfManagedPath', 'move2selfManagedPath', 'new_link', 'newLinkAndSelfManagedPath', 'copying', 'error', 'linking']" is not assignable to type "Literal['already_linked', 'relinking', 'fixing_broken_link', 'identical_files', 'backing_up_source', 'backing_up_target', 'relinking_to_new_target', 'moving_to_target', 'new_link', 'new_link_and_target', 'linking', 'copying', 'error']"
      Type "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['already_linked', 'relinking', 'fixing_broken_link', 'identical_files', 'backing_up_source', 'backing_up_target', 'relinking_to_new_target', 'moving_to_target', 'new_link', 'new_link_and_target', 'linking', 'copying', 'error']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['already_linked']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['relinking']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['fixing_broken_link']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['identical_files']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['backing_up_source']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['backing_up_target']" (reportArgumentType)
  /home/alex/code/machineconfig/src/machineconfig/profile/create.py:186:35 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "object" of type "OperationRecord" in function "append"
    Type "Literal['already_linked', 'relinking', 'fixing_broken_link', 'identical_files', 'backupConfigDefaultPath', 'backing_up_target', 'relink2newSelfManagedPath', 'move2selfManagedPath', 'new_link', 'newLinkAndSelfManagedPath', 'copying', 'error', 'linking']" is not assignable to type "Literal['already_linked', 'relinking', 'fixing_broken_link', 'identical_files', 'backing_up_source', 'backing_up_target', 'relinking_to_new_target', 'moving_to_target', 'new_link', 'new_link_and_target', 'linking', 'copying', 'error']"
      Type "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['already_linked', 'relinking', 'fixing_broken_link', 'identical_files', 'backing_up_source', 'backing_up_target', 'relinking_to_new_target', 'moving_to_target', 'new_link', 'new_link_and_target', 'linking', 'copying', 'error']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['already_linked']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['relinking']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['fixing_broken_link']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['identical_files']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['backing_up_source']"
        "Literal['backupConfigDefaultPath']" is not assignable to type "Literal['backing_up_target']" (reportArgumentType)
/home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:14:12 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:110:12 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:111:12 - error: Import "plotly.graph_objects" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:187:12 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:188:12 - error: Import "plotly.graph_objects" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:189:12 - error: Import "plotly.express" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:297:18 - error: "add_trace" is not a known attribute of "None" (reportOptionalMemberAccess)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:299:18 - error: "update_layout" is not a known attribute of "None" (reportOptionalMemberAccess)
/home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:4:8 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:6:6 - warning: Import "sqlalchemy.orm" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:7:6 - warning: Import "sqlalchemy" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:8:6 - warning: Import "sqlalchemy.engine" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:9:6 - warning: Import "sqlalchemy.ext.asyncio" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:10:6 - warning: Import "sqlalchemy.engine" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:11:6 - warning: Import "sqlalchemy.sql.schema" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:97:14 - warning: Import "sqlalchemy.pool" could not be resolved from source (reportMissingModuleSource)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/dbms.py:135:14 - warning: Import "sqlalchemy.pool" could not be resolved from source (reportMissingModuleSource)
/home/alex/code/machineconfig/src/machineconfig/utils/files/read.py
  /home/alex/code/machineconfig/src/machineconfig/utils/files/read.py:25:24 - error: Import "matplotlib.pyplot" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/read.py:28:24 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/read.py:31:24 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/read.py:70:16 - error: Import "numpy" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/utils/files/read.py:97:16 - error: Import "polars" could not be resolved (reportMissingImports)
16 errors, 8 warnings, 0 informations
